"""Generate immutable entity classes from the V2 business RDF. Run from repository root."""

import hashlib
import re
from pathlib import Path

from rdflib import OWL, RDF, RDFS, Graph, URIRef

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "ontology/graph/diabetes-ontology-v2.rdf"
NS = "http://example.org/ontology/diabetes-care-ontology-v2/"


def snake(name):
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def generate():
    graph = Graph().parse(SOURCE)
    lines = [
        "# Generated by scripts/generate_domain.py; do not edit.",
        "from __future__ import annotations",
        "from dataclasses import dataclass",
        "from datetime import date, datetime",
        "from decimal import Decimal",
        "from typing import ClassVar",
        "",
        f"ONTOLOGY_SHA256 = {hashlib.sha256(SOURCE.read_bytes()).hexdigest()!r}",
        "",
    ]
    types = {
        "string": "str",
        "integer": "int",
        "decimal": "Decimal",
        "boolean": "bool",
        "date": "date",
        "dateTime": "datetime",
    }
    names = []
    for cls in sorted(graph.subjects(RDF.type, OWL.Class), key=str):
        name = str(cls).removeprefix(NS)
        names.append(name)
        lines += [
            "@dataclass(frozen=True, kw_only=True)",
            f"class {name}:",
            f"    ontology_iri: ClassVar[str] = {str(cls)!r}",
            "    iri: str",
        ]
        fields = {}
        for prop in sorted(graph.subjects(RDFS.domain, cls), key=str):
            local = str(prop).removeprefix(NS)
            field = snake(local.split("_", 1)[-1])
            if field in fields:
                raise ValueError(f"Duplicate field {name}.{field}")
            target = str(graph.value(prop, RDFS.range))
            if (prop, RDF.type, OWL.ObjectProperty) in graph:
                cardinality = str(graph.value(prop, URIRef(NS + "cardinality")))
                if cardinality not in {"one-to-one", "many-to-one", "one-to-many", "many-to-many"}:
                    raise ValueError(f"Unknown cardinality: {prop}")
                kind = "tuple[str, ...]" if cardinality.endswith("to-many") else "str"
                default = "()" if kind.startswith("tuple") else "None"
                annotation = kind if default == "()" else kind + " | None"
            else:
                kind = types[target.split("#")[-1]]
                annotation, default = kind + " | None", "None"
            fields[field] = {"iri": str(prop), "range": target}
            lines.append(f"    {field}: {annotation} = {default}")
        lines += [f"    rdf_fields: ClassVar[dict] = {fields!r}", "", ""]
    lines.append("ENTITY_TYPES = {" + ", ".join(f"{n}.ontology_iri: {n}" for n in names) + "}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    (ROOT / "src/dmo/domain/generated.py").write_text(generate())
